# Generated by Django 3.0.5 on 2020-04-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendo_matic', '0002_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='value',
            field=models.IntegerField(),
        ),
    ]
