# Generated by Django 3.0.5 on 2020-04-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendo_matic', '0003_auto_20200416_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_coins', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
            ],
        ),
    ]
